### ISSUE TITLE
Paid Enhancements?

### ISSUE THREAD

**Issue by TonyValenti** [serilog-contrib/serilog-sinks-richtextbox#25]
Hi @augustoproiete -
I really want to get some of these enhancements implemented.  Can you give me an idea on a cost and a timeline?

**Comment by augustoproiete** [comment]
Hey @TonyValenti, I haven't forgotten about this project but have been short on time. I'll reach out to a couple of friends to see if they can take it, and I can help reviewing the PR & getting it merged/shipped, and will message you.
